version: "3.7"

services:
  zookeeper:
    image: "bitnami/zookeeper:3.6.2"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:2.6.0"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  tokensdb:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    volumes:
      - ./services/tokens/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  tokens:
    build:
      context: services/tokens
    image: tokens
    environment:
      - APP_DSN=postgres://app:pass@tokensdb:5432/db
      - APP_BROKER_URL=kafka:9092
    ports:
      - 9999:9999
    depends_on:
      - kafka
      - tokensdb

  payments:
    build:
      context: services/payments
    image: payments
    environment:
      - APP_BROKER_URL=kafka:9092
    depends_on:
      - kafka
